import { Recipe } from './RecipeTypes';

// Core set of 12 recipes
export const RECIPES: Recipe[] = [
  {
    id: 1,
    title: "Classic Soul Butter Tart",
    author: "Grandma Rose",
    authorAvatar: "placeholder-avatar",
    image: "placeholder-tart-image",
    description: "A perfect blend of traditional Canadian butter tarts with soul food influences. This recipe has been passed down through generations.",
    prepTime: "30 mins",
    cookTime: "25 mins",
    totalTime: "55 mins",
    servings: 12,
    difficulty: "Medium",
    ingredients: [
      { amount: "2 cups", name: "all-purpose flour" },
      { amount: "1 cup", name: "unsalted butter", notes: "cold and cubed" },
      { amount: "½ cup", name: "ice water" },
      { amount: "1 cup", name: "packed brown sugar" },
      { amount: "2 large", name: "eggs" },
      { amount: "¼ cup", name: "maple syrup" },
      { amount: "1 tsp", name: "vanilla extract" },
      { amount: "¼ tsp", name: "salt" }
    ],
    instructions: [
      { step: 1, text: "Prepare the pastry by combining flour and cold butter" },
      { step: 2, text: "Mix in ice water until dough forms" },
      { step: 3, text: "Chill dough for 1 hour" },
      { step: 4, text: "Prepare filling by combining all ingredients" },
      { step: 5, text: "Fill tart shells and bake at 375°F for 25 minutes" }
    ],
    rating: 4.9,
    dateSubmitted: "2024-02-15",
    isApproved: true,
    votes: 124,
    comments: [],
    tags: ["Classic", "Traditional", "Family Recipe"],
    category: "Classic Tarts",
    isFeatured: true,
    allergens: ["Eggs", "Dairy", "Wheat"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 2,
    title: "Sweet Potato Butter Tart",
    author: "Chef Marcus",
    image: "placeholder-tart-image",
    description: "A soul food fusion creation combining sweet potato pie with classic butter tart.",
    prepTime: "45 mins",
    cookTime: "30 mins",
    totalTime: "1 hr 15 mins",
    servings: 8,
    difficulty: "Advanced",
    ingredients: [
      { amount: "2 cups", name: "all-purpose flour" },
      { amount: "1 medium", name: "sweet potato" },
      { amount: "¾ cup", name: "brown sugar" },
      { amount: "2 large", name: "eggs" },
      { amount: "½ cup", name: "heavy cream" },
      { amount: "1 tsp", name: "cinnamon" }
    ],
    instructions: [
      { step: 1, text: "Roast and mash sweet potato" },
      { step: 2, text: "Prepare pastry dough" },
      { step: 3, text: "Mix filling ingredients" },
      { step: 4, text: "Fill and bake tarts" }
    ],
    rating: 4.8,
    dateSubmitted: "2024-03-01",
    isApproved: true,
    votes: 89,
    comments: [],
    tags: ["Fusion", "Sweet Potato", "Innovative"],
    category: "Soul Food Fusion",
    isFeatured: true,
    allergens: ["Eggs", "Dairy", "Wheat"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 3,
    title: "Vegan Maple Butter Tart",
    author: "Sarah Green",
    image: "placeholder-tart-image",
    description: "A plant-based version of the classic butter tart that doesn't compromise on taste.",
    prepTime: "40 mins",
    cookTime: "25 mins",
    servings: 12,
    difficulty: "Medium",
    ingredients: [
      { amount: "2 cups", name: "all-purpose flour" },
      { amount: "1 cup", name: "vegan butter" },
      { amount: "1 cup", name: "maple syrup" },
      { name: "Plant-based egg substitute", amount: "" },
      { name: "Coconut cream", amount: "" }
    ],
    instructions: [
      { step: 1, text: "Prepare vegan pastry" },
      { step: 2, text: "Mix filling ingredients" },
      { step: 3, text: "Fill tart shells" },
      { step: 4, text: "Bake until golden" }
    ],
    rating: 4.7,
    dateSubmitted: "2024-02-28",
    isApproved: true,
    votes: 56,
    comments: [],
    tags: ["Vegan", "Plant-Based", "Dairy-Free"],
    category: "Vegan & Alternative",
    allergens: ["Wheat"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 4,
    title: "Spiced Pumpkin Butter Tart",
    author: "Maya Johnson",
    image: "placeholder-tart-image",
    description: "A seasonal favorite combining pumpkin pie spices with butter tart filling.",
    prepTime: "35 mins",
    cookTime: "28 mins",
    servings: 10,
    difficulty: "Medium",
    ingredients: [
      { name: "Pastry dough", amount: "" },
      { name: "Pumpkin puree", amount: "" },
      { name: "Brown sugar", amount: "" },
      { name: "Pumpkin pie spice", amount: "" },
      { name: "Eggs", amount: "" }
    ],
    instructions: [
      { step: 1, text: "Mix pumpkin with spices" },
      { step: 2, text: "Prepare tart shells" },
      { step: 3, text: "Combine filling ingredients" },
      { step: 4, text: "Bake until set" }
    ],
    rating: 4.6,
    dateSubmitted: "2024-03-05",
    isApproved: true,
    votes: 42,
    comments: [],
    tags: ["Seasonal", "Pumpkin", "Fall Favorite"],
    category: "Seasonal Specials",
    allergens: ["Eggs", "Dairy", "Wheat"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 5,
    title: "Bourbon Pecan Butter Tart",
    author: "James Wilson",
    image: "placeholder-tart-image",
    description: "A Southern-inspired butter tart featuring bourbon and pecans.",
    prepTime: "30 mins",
    cookTime: "25 mins",
    servings: 12,
    difficulty: "Medium",
    ingredients: [
      { name: "Pastry dough", amount: "" },
      { name: "Pecans", amount: "" },
      { name: "Bourbon", amount: "" },
      { name: "Brown sugar", amount: "" },
      { name: "Butter", amount: "" }
    ],
    instructions: [
      { step: 1, text: "Toast pecans" },
      { step: 2, text: "Prepare bourbon filling" },
      { step: 3, text: "Fill tart shells" },
      { step: 4, text: "Bake until golden" }
    ],
    rating: 4.8,
    dateSubmitted: "2024-03-10",
    isApproved: true,
    votes: 78,
    comments: [],
    tags: ["Bourbon", "Pecan", "Southern"],
    category: "Soul Food Fusion",
    allergens: ["Eggs", "Dairy", "Wheat", "Tree Nuts"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 6,
    title: "Chocolate Hazelnut Butter Tart",
    author: "Lila Torres",
    image: "placeholder-tart-image",
    description: "A decadent tart filled with rich chocolate and roasted hazelnuts.",
    prepTime: "35 mins",
    cookTime: "30 mins",
    servings: 10,
    difficulty: "Medium",
    ingredients: [
      { name: "Pastry dough", amount: "" },
      { name: "Chocolate chips", amount: "1 cup" },
      { name: "Hazelnuts", amount: "1/2 cup, chopped" },
      { name: "Butter", amount: "1/2 cup" },
      { name: "Brown sugar", amount: "3/4 cup" }
    ],
    instructions: [
      { step: 1, text: "Melt chocolate and butter together." },
      { step: 2, text: "Mix with brown sugar and hazelnuts." },
      { step: 3, text: "Fill tart shells and bake." }
    ],
    rating: 4.7,
    dateSubmitted: "2024-03-15",
    isApproved: true,
    votes: 54,
    comments: [],
    tags: ["Chocolate", "Hazelnut", "Decadent"],
    category: "Seasonal Specials",
    allergens: ["Eggs", "Dairy", "Wheat", "Tree Nuts"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 7,
    title: "Maple Walnut Tart",
    author: "Ben Carter",
    image: "placeholder-tart-image",
    description: "Classic Canadian maple syrup with crunchy walnuts.",
    prepTime: "30 mins",
    cookTime: "25 mins",
    servings: 12,
    difficulty: "Easy",
    ingredients: [
      { name: "Pastry dough", amount: "" },
      { name: "Maple syrup", amount: "1 cup" },
      { name: "Walnuts", amount: "1 cup, chopped" },
      { name: "Eggs", amount: "2" },
      { name: "Brown sugar", amount: "1/2 cup" }
    ],
    instructions: [
      { step: 1, text: "Mix maple syrup, eggs, and brown sugar." },
      { step: 2, text: "Add walnuts." },
      { step: 3, text: "Fill tart shells and bake." }
    ],
    rating: 4.5,
    dateSubmitted: "2024-03-18",
    isApproved: true,
    votes: 33,
    comments: [],
    tags: ["Maple", "Walnut", "Classic"],
    category: "Classic Tarts",
    allergens: ["Eggs", "Wheat", "Tree Nuts"],
    reviews: [],
    cuisine: "Canadian"
  },
  {
    id: 8,
    title: "Lemon Blueberry Butter Tart",
    author: "Tina Lee",
    image: "placeholder-tart-image",
    description: "Bright lemon zest and juicy blueberries in a sweet tart shell.",
    prepTime: "40 mins",
    cookTime: "28 mins",
    servings: 10,
    difficulty: "Medium",
    ingredients: [
      { name: "Pastry dough", amount: "" },
      { name: "Blueberries", amount: "1 cup" },
      { name: "Lemon zest", amount: "1 tbsp" },
      { name: "Eggs", amount: "2" },
      { name: "Sugar", amount: "1/2 cup" }
    ],
    instructions: [
      { step: 1, text: "Mix blueberries, lemon zest, and sugar." },
      { step: 2, text: "Add eggs and combine." },
      { step: 3, text: "Fill shells and bake." }
    ],
    rating: 4.6,
    dateSubmitted: "2024-03-20",
    isApproved: true,
    votes: 41,
    comments: [],
    tags: ["Lemon", "Blueberry", "Fruit"],
    category: "Seasonal Specials",
    allergens: ["Eggs", "Wheat"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 9,
    title: "Gluten-Free Butter Tart",
    author: "Alex Kim",
    image: "placeholder-tart-image",
    description: "A gluten-free take on the classic, using almond flour pastry.",
    prepTime: "35 mins",
    cookTime: "25 mins",
    servings: 8,
    difficulty: "Medium",
    ingredients: [
      { name: "Almond flour", amount: "2 cups" },
      { name: "Butter", amount: "1/2 cup" },
      { name: "Eggs", amount: "2" },
      { name: "Brown sugar", amount: "1/2 cup" },
      { name: "Maple syrup", amount: "1/4 cup" }
    ],
    instructions: [
      { step: 1, text: "Mix almond flour, butter, and eggs for pastry." },
      { step: 2, text: "Prepare classic filling." },
      { step: 3, text: "Bake as usual." }
    ],
    rating: 4.4,
    dateSubmitted: "2024-03-22",
    isApproved: true,
    votes: 29,
    comments: [],
    tags: ["Gluten-Free", "Alternative"],
    category: "Vegan & Alternative",
    allergens: ["Eggs", "Tree Nuts"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 10,
    title: "Espresso Caramel Tart",
    author: "Derek Smith",
    image: "placeholder-tart-image",
    description: "Rich espresso flavor blended with gooey caramel in a tart shell.",
    prepTime: "45 mins",
    cookTime: "30 mins",
    servings: 12,
    difficulty: "Advanced",
    ingredients: [
      { name: "Pastry dough", amount: "" },
      { name: "Espresso", amount: "2 shots" },
      { name: "Caramel", amount: "1 cup" },
      { name: "Eggs", amount: "2" },
      { name: "Sugar", amount: "1/2 cup" }
    ],
    instructions: [
      { step: 1, text: "Prepare caramel with espresso." },
      { step: 2, text: "Mix with eggs and sugar." },
      { step: 3, text: "Bake in tart shells." }
    ],
    rating: 4.3,
    dateSubmitted: "2024-03-25",
    isApproved: true,
    votes: 18,
    comments: [],
    tags: ["Espresso", "Caramel", "Coffee"],
    category: "Soul Food Fusion",
    allergens: ["Eggs", "Wheat"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 11,
    title: "Raspberry Almond Tart",
    author: "Priya Patel",
    image: "placeholder-tart-image",
    description: "Sweet almond filling topped with fresh raspberries.",
    prepTime: "38 mins",
    cookTime: "27 mins",
    servings: 10,
    difficulty: "Medium",
    ingredients: [
      { name: "Pastry dough", amount: "" },
      { name: "Almond meal", amount: "1 cup" },
      { name: "Raspberries", amount: "1 cup" },
      { name: "Eggs", amount: "2" },
      { name: "Sugar", amount: "1/2 cup" }
    ],
    instructions: [
      { step: 1, text: "Prepare almond filling." },
      { step: 2, text: "Spread in tart shell and top with raspberries." },
      { step: 3, text: "Bake until golden." }
    ],
    rating: 4.6,
    dateSubmitted: "2024-03-27",
    isApproved: true,
    votes: 24,
    comments: [],
    tags: ["Raspberry", "Almond", "Fruit"],
    category: "Seasonal Specials",
    allergens: ["Eggs", "Tree Nuts", "Wheat"],
    reviews: [],
    cuisine: "Unknown"
  },
  {
    id: 12,
    title: "No-Bake Coconut Tart",
    author: "Jordan Nguyen",
    image: "placeholder-tart-image",
    description: "A quick, no-bake tart with coconut and a date-nut crust.",
    prepTime: "20 mins",
    cookTime: "0 mins",
    servings: 8,
    difficulty: "Easy",
    ingredients: [
      { name: "Dates", amount: "1 cup" },
      { name: "Coconut flakes", amount: "1 cup" },
      { name: "Almonds", amount: "1/2 cup" },
      { name: "Coconut cream", amount: "1/2 cup" }
    ],
    instructions: [
      { step: 1, text: "Blend dates, coconut, and almonds for crust." },
      { step: 2, text: "Press into tart pan and chill." },
      { step: 3, text: "Fill with coconut cream and serve." }
    ],
    rating: 4.2,
    dateSubmitted: "2024-03-30",
    isApproved: true,
    votes: 17,
    comments: [],
    tags: ["No-Bake", "Coconut", "Alternative"],
    category: "Vegan & Alternative",
    allergens: ["Tree Nuts"],
    reviews: [],
    cuisine: "Unknown"
  }
];
